spring.application.name=messagesApp

spring.datasource.url=jdbc:postgresql://localhost:5432/messagesDB
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA tweak (optional)
spring.jpa.hibernate.ddl-auto=update

# Disable springdoc data-rest integration to avoid conflicts
springdoc.show-spring-data-rest=false